[tox]
envlist = py3.{10-13}-{pytest,pre-commit}
min_version = 4.25
work_dir = {env:USERPROFILE:"."}/.cache/.tox/{env:VIRTUAL_ENV_PROMPT}

[testenv]
commands =
    pytest: pytest {tty:--color=yes} {posargs}
    pre-commit: pre-commit run  {tty:--color=always} -a
deps =
    pre-commit: pre-commit
    pytest: .[testing]

passenv =
    MYPY_CACHE_DIR
    PYTHONPYCACHEPREFIX

skip_install = pre-commit: true
